### PR TITLE
Add BUILD_PARALLEL_COMBINATIONS, fix readline bug

### PR DESCRIPTION
**Pull request by multiplemonomials**
I thought it would be a good thing to support building combinations of parallelizations (e.g. `cpptraj.OMP.MPI.cuda`), but this increased the build time by a massive amount when building with lots of parallelizations.  So, I added a new option, `BUILD_PARALLEL_COMBINATIONS`, which turns this feature on or off.  `BUILD_PARALLEL_COMBINATIONS` is disabled when building inside Amber.

This PR also fixes a bug that was causing a build error when Readline was disabled: I used the wrong CMake code to apply the `USE_SANDERLIB` definition, and it was erasing all definitions before it in the script.

### CODE REVIEW

**Comment by hainm** [comment]
@multiplemonomials are you meant to make "cmake" as a submodue of cpptraj?

https://github.com/Amber-MD/cpptraj/pull/567/files#diff-272ceadb8458515b2ae4b5630a6029cc

**Comment by multiplemonomials** [comment]
It is a submodule of `cpptraj`.

**Comment by drroe** [comment]
@multiplemonomials Sorry, just saw this - I've been traveling. I'll try updating the branch and merging today.

**Comment by multiplemonomials** [comment]
No problem, hope you're enjoying your trip!

**Pull request merged**
