### PR TITLE
Code cleanup.

### PR DESCRIPTION
**Pull request by drroe**
This PR is code cleanup related to some of the issues brought up by @ValZapod in #754.

### CODE REVIEW

**Comment by drroe** [comment]
Note that the PGI build passed this time - what a frustrating compiler...

**Comment by drroe** [comment]
> Note that the PGI build passed this time - what a frustrating compiler...

Just kidding - I forgot @swails recently allowed that to fail silently. My bad.

**Comment by swails** [comment]
> Just kidding - I forgot @swails recently allowed that to fail silently. My bad.

I can make it fail without failing the build, but have it still post a comment on the PR that the PGI build failed.  As it stands right now, you have to go digging to see if PGI passed or failed.

**Comment by swails** [comment]
Wow that was confusing.  I'll rephrase:

I can make the build post the PGI failure as a PR comment without making the build itself fail.  That'll at least let you know if PGI failed without having to go on a hunt.

**Pull request merged**
