### PR TITLE
Added new citation information for our recent publication in JCC.

### PR DESCRIPTION
**Pull request by gosldorf**
Yup, one line change, just needs to be done before I forget. Thanks for any help.

### CODE REVIEW

**Comment by swails** [comment]
Can you break this up into 4 commits (and 3 PRs) for pytraj? :)

**Comment by hainm** [comment]
> pytraj

Did you mistaken with `cpptraj`?

**Comment by swails** [comment]
No, just teasing you on your copious number of commits and PRs per line of code :)

**Comment by hainm** [comment]
> PRs per line of code

lol. I can make several PRs just for fixing my typos (and re-fix, re-fix, ...) :D

**Comment by drroe** [comment]
:+1:

**Pull request merged**
