### PR TITLE
Try to omit ReadLine.o and Cpptraj.o from libcpptraj

### LINKED ISSUE #220: remove readline + libsander in libcpptraj
I am testing pytraj in amber and got undefined symbol that relates to readline. Can  you remove it from libcpptraj since there is no use here. thanks.

> libcpptraj.so: undefined symbol: rl_attempted_completion_function

### PR DESCRIPTION
**Pull request by swails**
Replaces #221
Fixes #220

### CODE REVIEW

**Comment by hainm** [comment]
I got 

`ImportError: /home/haichit/pytraj_git/pytraj/cpptraj/lib/libcpptraj.so: undefined symbol: _ZN7CpptrajD1Ev`

`pytraj` still need `Cpptraj.h` to get cpptraj version internally.

```python
cdef extern from "Cpptraj.h":
    cdef cppclass Cpptraj:
        @staticmethod
        string Defines()

__cpptraj_version__ = CPPTRAJ_VERSION_STRING.decode()
__cpptraj_internal_version__ = CPPTRAJ_INTERNAL_VERSION.decode()
```

**Comment by rmcgibbo** [comment]
Is something passing a flag to the linker to ignore undefined all symbols? IMO, the linked shouldn't _let you_ compile a shared object like that that has undefined symbols that aren't external.

**Comment by hainm** [comment]
@rmcgibbo  I am not sure if there is a flag or not. This is the command

`gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/u1/haichit/pytraj_git/pytraj/cpptraj/src/ -I/u1/haichit/pytraj_git/pytraj/pytraj/ -I/home/haichit/anaconda3/include/python3.5m -c pytraj/cpp_options.cpp -o build/temp.linux-x86_64-3.5/pytraj/cpp_options.o -O0 -ggdb -fopenmp
`

`g++ -pthread -shared -L/home/haichit/anaconda3/lib -Wl,-rpath=/home/haichit/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/pytraj/cpp_options.o -L/u1/haichit/pytraj_git/pytraj/cpptraj/lib/ -L/home/haichit/anaconda3/lib -lcpptraj -lpython3.5m -o build/lib.linux-x86_64-3.5/pytraj/cpp_options.cpython-35m-x86_64-linux-gnu.so -O0 -ggdb -fopenmp
`

**Comment by rmcgibbo** [comment]
Perhaps this is not the default. http://stackoverflow.com/questions/2356168/force-gcc-to-notify-about-undefined-references-in-shared-libraries

If you pass  `-Wl,--no-undefined` to g++, does that trigger the error?

**Comment by hainm** [comment]
@rmcgibbo works great. thanks.

```bash
/home/haichit/pytraj_git/pytraj/pytraj/cpp_options.cpp:957: undefined reference to `Cpptraj::Defines()'
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1
make: *** [install] Error 1
```

**Comment by swails** [comment]
@hainm -- I take it that this PR doesn't work for you, and you'll do something else (like compile with `-noreadline` or something)?  Should I just close this PR?

**Comment by hainm** [comment]
yes, close it. thanks.

**Pull request closed without merging**
