### PR TITLE
Updated tests

### PR DESCRIPTION
**Pull request by drroe**
This PR enables all tests to be run by default. The shorter test suite can still be run if desired via `make test.short`. Also adds 16 new tests.

### CODE REVIEW

**Comment by drroe** [comment]
The remaining test differences on AppVeyor appear innocuous. The first diff is from Test_General:
```
a2.dat.gz.save a2.dat.gz are different.
Binary files a2.dat.gz.save and a2.dat.gz differ
```
Not sure why this is - maybe due to differing newline chars (and I'm guessing `--strip-trailing-cr` doesn't work because the files are binary)? Best way to address this may be to compare decompressed files via `zcat`.

The second is from Test_GIST:
```
gist.out.save gist.out are different.
5797c5797
< 5794 -5.25 4.25 8.25 1 23.9357 0 -1.02279 -1.27848 0 0 0.87562 1.09453 0 0 0 0 -0.763227 1.58257 0.662926 1.8779 3.2 4 0.666174 
---
> 5794 -5.25 4.25 8.25 1 23.9357 0 -1.02279 -1.27848 0 0 0.87562 1.09452 0 0 0 0 -0.763227 1.58257 0.662926 1.8779 3.2 4 0.666174 
5833c5833
< 5830 -5.25 4.75 8.25 1 23.9357 0 -1.02279 -1.27848 0 0 0.87562 1.09453 0 0 0 0 -0.431269 -1.02303 1.51458 1.87791 5.6 7 0.675507 
---
> 5830 -5.25 4.75 8.25 1 23.9357 0 -1.02279 -1.27848 0 0 0.87562 1.09452 0 0 0 0 -0.431269 -1.02303 1.51458 1.87791 5.6 7 0.675507 
6144c6144
< 6141 -5.25 9.25 1.75 1 23.9357 0 -0.641073 -0.801341 0 0 -0.643096 -0.80387 0 0 0 0 0.385332 0.889725 -1.60824 1.87791 3.2 4 0.80246 
---
> 6141 -5.25 9.25 1.75 1 23.9357 0 -0.641073 -0.801341 0 0 -0.643097 -0.803871 0 0 0 0 0.385332 0.889725 -1.60824 1.87791 3.2 4 0.80246 
40361c40361
< 40358 5.75 0.75 -7.75 2 47.8714 0 -5.06887 -3.16804 1.9417 1.21356 -0.205834 -0.128646 -1.56727 -0.979543 -15.1239 -9.45245 1.05082 -2.09259 -1.06925 2.57419 8.8 5.5 0.725054 
---
> 40358 5.75 0.75 -7.75 2 47.8714 0 -5.06887 -3.16804 1.9417 1.21356 -0.205835 -0.128647 -1.56727 -0.979543 -15.1239 -9.45245 1.05082 -2.09259 -1.06925 2.57419 8.8 5.5 0.725054 
  1 out of 6 comparisons failed.
```
This appears to be round-off, perhaps due to the slightly different implementation of printf in mingw-64? Not sure what the best way to address this is. I don't want to implement something like Amber's `dacdif` if I can avoid it. I also don't want this to show up as a failure...

**Comment by hainm** [comment]
yeah, it's round-off

> -0.205834 
> -0.205835

**Comment by rmcgibbo** [comment]
Does the cpptraj test framework support the concept of "skipped" tests or tests with "allowed failures"? Could just skip these tests on windows.

**Comment by hainm** [comment]
>  Could just skip these tests on windows.

agree.

**Comment by drroe** [comment]
Since the appveyor failure is its own fault, not cpptraj's:
```
Failed to provision build worker virtual machine in Google Compute Engine cloud. Try restarting build later.
```
and since the last 6 Travis-CI builds have passed with flying colors, I'm going to merge this now and worry about appveyor later if necessary.

**Comment by drroe** [comment]
Appveyor build finally ran and completed successfully (with the 2 expected warnings):
https://ci.appveyor.com/project/drroe/cpptraj-aof9y/build/1.0.33
Thanks for all of the helpful comments!

**Pull request merged**
