### PR TITLE
New approach to building libcpptraj

### PR DESCRIPTION
**Pull request by drroe**
This PR represents a new approach to building libcpptraj. Instead of having to determine the pieces that will go into or be excluded from libcpptraj at configure time (e.g. having to specify `-nosanderlib` etc), make it a build time decision. This is done by having files that are different for cpptraj/libcpptraj be compiled into separate objects for libcpptraj using a libcpptraj-specific define, `-DLIBCPPTRAJ`. These objects have a `.LIBCPPTRAJ.o` extension (instead of just `.o`); this is a similar strategy to how SANDER compiles for LES.

The advantage of this is that no matter how cpptraj is configured, libcpptraj can still be built, so e.g. cpptraj can have sanderlib support, but the build does not have to be reconfigured to compile libcpptraj. Having separate objects for cpptraj/libcpptraj also means that parallel builds with both targets active will work.

This should hopefully address #220.

### CODE REVIEW

**Comment by drroe** [comment]
@hainm I did  some testing with pytraj and it seemed to build fine, but I will be interested to hear your opinion. Ostensibly this should make it easier to make a trimmed-down libcpptraj in the future.

**Comment by hainm** [comment]
thanks. I will test tonight.

**Comment by hainm** [comment]
can you also merge this PR to amber repo too?

**Comment by drroe** [comment]
Done.

**Comment by hainm** [comment]
thx

**Pull request merged**
