### PR TITLE
Improve the efficiency of the atomicfluct command

### PR DESCRIPTION
**Pull request by drroe**
Use an integer mask instead of character mask and only deal with the atoms that are selected.

### CODE REVIEW

**Comment by drroe** [comment]
The Mac backlog is nuts...https://www.traviscistatus.com/

**Comment by hainm** [comment]
I only test MacOS on my computer. :D Too long to wait for travis.

**Comment by swails** [comment]
I can set up my Mac mini as a Jenkins slave and get OS X testing done there if you think it's worthwhile.

**Comment by drroe** [comment]
@swails I may just take you up on that...

**Pull request merged**
