### PR TITLE
Add the 'time' action

### PR DESCRIPTION
**Pull request by drroe**
Add the `time` action for modifying time information in frames.
```
  [help time]
	{time0 <initial time> dt <step> [update] | remove}
  Add, modify, or remove time information from each frame.
    time0 <initial time> : Time of the first frame (ps).
    dt <step>            : Time step between frames (ps).
    update               : If specified, modify any existing time info.
    remove               : Remove any time info from frame.
```
Also adds tests for each of these modes and updates the manual.

### CODE REVIEW

**Comment by drroe** [comment]
It's not clear to me from the logs why the parallel Jenkins build failed. Going to try and retrigger.

**Comment by drroe** [comment]
run jenkins

**Comment by drroe** [comment]
Figured it out - needed to protect the test in parallel; NetCDF writes in parallel require parallel NetCDF which none of the MPI test rigs currently have. I wonder if I should consider bundling parallel NetCDF with cpptraj.

**Comment by drroe** [comment]
Appveyor is still queued, but since Travis, Jenkins, and LGTM are happy I'm going to go ahead and merge now.

**Comment by swails** [comment]
> Figured it out - needed to protect the test in parallel; NetCDF writes in parallel require parallel NetCDF which none of the MPI test rigs currently have.

[You can always add it to the Dockerfile](https://github.com/Amber-MD/cpptraj/blob/master/devtools/ci/jenkins/Dockerfile).

Then the Jenkins builds will have it, regardless of which slave it runs on.

**Pull request merged**
