### PR TITLE
make code consistent: use DSL and DFL

### PR DESCRIPTION
**Pull request by hainm**
'datasetlist' --> 'DSL' (to be consistent with all Action class)
'DFLin' --> "DFL"

### CODE REVIEW

**Comment by hainm** [comment]
@drroe let me know what do you think.

**Comment by swails** [comment]
`DSLin` -> `DSL` and `DFLin` -> `DFL` are probably bad changes.  The former names are examples of Hungarian notation done correctly.  `datasetlist` -> `DSL` probably improves consistency and are good changes.

@drroe will have stronger opinions than I (and stronger justification as well), but that's my "more-outsider's" opinion.

**Comment by hainm** [comment]
@swails 

after playing with cpptraj code for a while, it seems to me that cpptraj uses only a single DataSetList to store everything (input (add topology, reference, dataset, ...) and output).

But I agree that @drroe will have stronger opinion. This PR update is done by auto-replacing without carefully reading the code. :D

**Comment by hainm** [comment]
uhm, no longer need this PR (check https://github.com/Amber-MD/cpptraj/pull/111)

**Pull request closed without merging**
