### PR TITLE
Add density calculation to 'volume'

### PR DESCRIPTION
**Pull request by drroe**
Since we're halfway there anyway in volume. Can now specify `density` keyword for `volume` action to get system density. Also makes it clear what units the data are in either case. Adds tests for both.

### CODE REVIEW

**Comment by drroe** [comment]
Appveyor false positive. Merging.

**Comment by hainm** [comment]
I have hard time with density command and density in volume command.

**Comment by drroe** [comment]
Unfortunately `density` got scooped up by Hans Loeffler; his command does density along specific coordinates, not the entire system density. Instead of trying to force a weird command name I folded it into volume since they are related anyway. I guess I could either try to fold it in to the existing `density`  command somehow, or call it something like `systemdensity`? I don't like any of the options, including the one I went with.

Ideally I'd rename `density` to `coordinatedensity` and use `density` but then backwards compat. is broken...

**Comment by hainm** [comment]
> Ideally I'd rename density to coordinatedensity and use density but then backwards compat. is broken...

Can we make SUPER NOISY warning in AT18 and make change in AT19? sometimes we really need to do that.

**Comment by drroe** [comment]
> Can we make SUPER NOISY warning in AT18 and make change in AT19? sometimes we really need to do that.

I think a better alternative will be for me to fold it into the existing `density` command somehow. I'll look into this.

**Comment by hainm** [comment]
Sounds a good plan. (I thought the same thing for pytraj).

**Pull request merged**
