### PR TITLE
Add support for reading Desmond DTR (Anton) trajectories

### PR DESCRIPTION
**Pull request by drroe**
Makes use of the DTR plugin from VMD (used with permission) under the hood. Supports only reads at present, but does work in parallel. There is no test yet since the smallest DTR trajectory I have is ~4 GB - will have to add a test in the future.

### CODE REVIEW

**Comment by hainm** [comment]
image

**Comment by drroe** [comment]
https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fpytraj/detail/pytraj/153/pipeline

Why does it hang?

**Comment by hainm** [comment]
uhm, not sure. I already exclude the parallel tests
`
pytest -vs --ignore=test_parallel_pmap --ignore=test_run_mpi.py --ignore=test_energy/test_pmap_sander.py --ignore=test_parallel_mpi --ignore=test_actionlist.py
`
let's try to finish this (switch to py3): https://github.com/Amber-MD/cpptraj/pull/790

PS: I have never had this issue with pytraj on linux (either from travis or from my docker image).

**Comment by hainm** [comment]
uhm, It's not a python version issue either.

This PR run with python 3.
```
platform linux -- Python 3.7.4, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /opt/conda/bin/python

cachedir: .pytest_cache

rootdir: /iscratch/jenkins-cpu/workspace/amber-github/pytraj

collecting ... cpptraj_test_dir /cpptraj/test

test_vs_cpptraj

test_frame_indices

test_simplified_codes

test_dssp_allatoms

/iscratch/jenkins-cpu/workspace/amber-github/pytraj/tests/test_energy

amberhome 

collected 420 items



run_simple_test.py::TestRunnable::test_Dataset try to make all dataset stuff

PASSED

run_simple_test.py::TestRunnable::test_create_ try to make all analysis objects

PASSED

run_simple_test.py::TestRunnable::test_create_actions try to make all action objects

PASSED

run_simple_test.py::TestRunnable::test_geometry try to make structure-related objects

PASSED

run_simple_test.py::TestRunnable::test_import try to load sample data

try to make all action objects

try to make all analysis objects

try to make all dataset stuff

try to make structure-related objects

try to create Trajectory-like objects

other stuff. throw all tests don't belong anywhere else here

OK

PASSED

run_simple_test.py::TestRunnable::test_loading PASSED

run_simple_test.py::TestRunnable::test_other other stuff. throw all tests don't belong anywhere else here

PASSED

test_crdframes.py::TestCrdFrames::test_crdframes PASSED

test_createcrd.py::TestCreateCRD::test_autoimage_rms_strip Sending interrupt signal to process
```

**Comment by drroe** [comment]
Jenkins fail is a pytraj hang - merging.

**Pull request merged**
