### PR TITLE
Move OS X tests to Jenkins

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
The tests should finally be working (working out the last issue with the CUDA tests was tricky -- I had to add the `jenkins` user to the `video` group to give it access to the GPUs).

But this should be ready to go finally!  OS X tests are now officially on Jenkins.  If this server ever goes away, you can just uncomment the OS X line in the `.travis.yml` file to bring it back.  The tests should all finish much faster now

**Comment by drroe** [comment]
Outstanding stuff Jason - thanks!

**Pull request merged**
