### PR TITLE
Numerous fixes and enhancements

### PR DESCRIPTION
**Pull request by drroe**
This PR covers a lot of ground.

- Address #96 for IRED output labels.
- Address #100; add `name` keyword for `parm` and `reference` commands which can be used in place of tags.
- Correctly handle file name wildcards on the command line for `-p`, `-y` etc ( #109 ). 
- Add `-d` and `-w` command line flags for reading and writing data sets from/to files (which also enables command-line conversion of data files).
- Add dihedral co-variance matrix tests ( #243 ), as well as tests for `curvefit`, `multicurve`, `avg`, and `vectormath`.
- Add data set scalar math functionality for 2D and 3D data sets (min, max, avg, etc).
- Add `allframes` keyword to `nastruct` to allow finding of base pairs every frame (not parallel-enabled yet).
- Fix issue where in `nastruct` step parameters were being calculated even if base pair parameters were not - now correctly set to 0.0 when this is the case.
- Add `calcnohb` keyword to calculate parameters even if base pairing not detected (no hbonds).
- nastruct: Add BP to base pair output, which is 1 if base pair is present (number hbonds > 0) and 0 otherwise. Also add Zp to base pair step output.
- Fix `nastruct` in parallel when base pairing changes in a run.
- Attempt to get tests working with MPI in Travis ( #145 ).
- `avg` analysis now uses data set/data file framework.
- Allow either vector to be of size 1 in `vectormath`, which allows vec OP vec(n) math.
- Add `nomod` keyword to `rms` command to prevent modification of coordinates during calculation of RMSD and adds a test for it.

### CODE REVIEW

**Comment by drroe** [comment]
OK, I clearly don't know enough about Travis. I'm having all kinds of weird issues. The current problem is 
```
E: Unable to locate package openmpi
```
But it seems like openmpi is on the whitelist:
https://github.com/travis-ci/apt-package-whitelist/blob/7a5250869012848f35bc16f5d0572749bbc84e39/ubuntu-precise#L9121-L9129

I'm going to keep at this for a little bit longer but if I can't figure it out I'll just disable the Travis MPI build for this PR.

**Comment by hainm** [comment]
@drroe  can you check this?

https://github.com/mpi4py/mpi4py/blob/master/conf/travis/install-mpi.sh

mpi4py use MPI on travis.

**Comment by drroe** [comment]
Hmm - removing the `openmpi` package did seem to do the trick - build and most tests succeeded. The ones that failed all do so with:
```
[testing-worker-linux-docker-2b86ccd2-3381-linux-1:10951] *** An error occurred in MPI_Reduce
[testing-worker-linux-docker-2b86ccd2-3381-linux-1:10951] *** on communicator MPI COMMUNICATOR 3 SPLIT FROM 0
[testing-worker-linux-docker-2b86ccd2-3381-linux-1:10951] *** MPI_ERR_ARG: invalid argument of some other kind
[testing-worker-linux-docker-2b86ccd2-3381-linux-1:10951] *** MPI_ERRORS_ARE_FATAL (your MPI job will now abort)
```
The failing tests are Test_AtomicCorr, Test_Grid (grid generation from bounds), and Test_Matrix. I haven't seen this error before with mvapich2 or mpich, so I'll have to try to reproduce tomorrow.

**Comment by drroe** [comment]
OK, I think I have fixed the OpenMPI issues. Turns out OpenMPI gets cranky if MPI_Reduce() is called with a null pointer, even if the count is 0 (this isn't an issue with mpich/mvapich). Should be fixed now (I hope).

**Comment by drroe** [comment]
Now there is a new failure in Test_Cluster_TrajWrites. It didn't appear in the previous build and I can't reproduce it locally (trying to replicate the Travis environment as close as possible; GNU 4.6.2 and OpenMPI 1.4.5). I'll re-trigger the build and see if the same error happens. If it does, this may have to be one of the cases that's allowed to fail for now.

**Comment by drroe** [comment]
OK, at long last the Travis build seems OK. I'll have to keep an eye out for transient failures in `Test_Cluster_TrajWrites`, which may indicate some weird subtle bug somewhere, but for now this seems good to merge (finally).

**Comment by hainm** [comment]
@drroe  are you considering change `nomod` (rms) to something easier to remember?

I chose `update_coordinate` in pytraj.

**Comment by swails** [comment]
Mr. "let's change `coordinates` to `xyz` to save typing"?? `nomod` -> `update_coordinates`?

What have you done with Hai? :smiley:

**Comment by hainm** [comment]
:P 

This is my rational.

`xyz` commonly used in some other python packages (including mdtraj, ...). And people seems oftenly use `xyz` (traj.xyz), so I would like to keep it to make it short. 

For example, in this nglview, it have similar code wrapping for mdtraj and pytraj (IMO, it's better to share similiar API): https://github.com/arose/nglview/blob/master/nglview/__init__.py#L148-L193

Per `update_coordinates` in `pytraj.rmsd`, I don't think this will be frequently used (including myself), so I leave it that way. (`update_xyz=True` seems vague to me).

**Comment by hainm** [comment]
but  people can change their mind too =))

I used to suggest to use `as_structure=True` for parmed but after using `parmed` for a while, I prefer to use `structure=True`, look prettier.

**Comment by drroe** [comment]
> are you considering change nomod (rms) to something easier to remember?

`nomod` = "no modify", which I don't think is that hard to remember. It's also consistent with the other option keywords `nofit` and `norotate`, so I will leave this as-is.

**Comment by hainm** [comment]
nomod -> nomodify? (norot -> norotate) :D

**Comment by hainm** [comment]
anyway, just minor thing.

**Pull request merged**
