### PR TITLE
Add support for reduce-generated PDB files.

### PR DESCRIPTION
**Pull request by swails**
@hainm -- see if this does the trick...

### CODE REVIEW

**Comment by hainm** [comment]
ok. I will test it.

**Comment by drroe** [comment]
Thanks Jason.
Ugh, they couldn't just use one of the existing like 50 or so tags? Had to come up with a non-standard one?

**Comment by hainm** [comment]
I just tried both cpptraj and parmed. They works with old reduce now. thanks.

**Comment by swails** [comment]
> Ugh, they couldn't just use one of the existing like 50 or so tags? Had to come up with a non-standard one?

I know, right?  It wasn't actually the parsing that didn't work, it was the format auto-detection...

**Pull request merged**
