### PR TITLE
Add Jenkins CI

### PR DESCRIPTION
**Pull request by swails**
The goal here is to add to the CI support for cpptraj.  This adds a recipe to run on my desktop with the Intel compilers and MPI, OpenMP, and serial.

It also utilizes the MKL.  Preliminary tests show 3 tests failing, but this should hopefully give output to look at.

@drroe, @hainm, and @dacase -- I have login credentials to the Jenkins system for you if you want to email me privately.

### CODE REVIEW

**Comment by swails** [comment]
Also, to re-run Jenkins, you just need to post the following in a comment on the PR:

run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by hainm** [comment]
minor point: may be 

```
[run jenkins]
```

(which is similar  to `[ci skip]` on travis, circleci`) :D

**Comment by swails** [comment]
The NaN errors I believe are a result of libsander not being linked (SPAM tests fail when sander is not available).  The other one is the curve fit, I believe.  I'm looking into it and will try to get a fix pushed up soon.

**Comment by swails** [comment]
btw, @hainm -- you can put [] around the r u n  j e n k i n s keywords and it will work too.  It's a permissive regex.

**Comment by drroe** [comment]
@swails seems very cool, thanks!
However, if I try to get 'details' on the Jenkins build my browser fails to connect to anything; just spins on jasonswails.com forever. Not sure if it's because of firewall issues where I am right now. I'll try from home tonight.

The curve fit errors I've seen before as well with Intel compilers. I tried tracking it down a while ago with no success. They were minor enough (and for me only occur with the likely little-used option `mexpk_penalty`) that I gave up. If you fix it I'll owe you a beer :-)

**Comment by swails** [comment]
@drroe -- I sent you an email with details about getting into the Jenkins server.  Make sure you're going to http://www.jasonswails.com:8888 -- if it spins forever it's quite possibly because your network shuts down access to nonstandard ports (e.g., anything except 22 or 80).

As for the curve fit tests, I just increased the maximum iterations to 5000 on that test and GNU/Intel agree within tolerable limits.  Have a look at the diff and let me know if that's acceptable to you.

**Comment by swails** [comment]
It could also be that it's http and not https :)

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
@drroe -- I'm in the midst of reconfiguring my jenkins server to route through port 80 instead of 8888 -- go ahead and try to go to the build, but delete :8888 from the URL

**Comment by drroe** [comment]
This seems good now. I think I'll merge it first thing tomorrow. Outstanding stuff @swails

**Comment by swails** [comment]
Wait -- something's wrong: http://www.jasonswails.com:8888/job/cpptraj/10/COMPILER_FLAGS=-openmp/console

How do I run the OpenMP tests?... I'll have a look at the travis.yml file

**Comment by swails** [comment]
I was missing an `OPT=openmp` environment variable.  Any ideas why `make check` had a 0 exit status there?

In any case, this newest commit should fix things for good.

**Comment by drroe** [comment]
>  Any ideas why make check had a 0 exit status there?

Without the `openmp` flag it will just run the serial tests. If there is a serial build prior to the openmp one (which I think there is but cannot check since I'm behind a firewall right now) then the serial tests will run. If there is no cpptraj binary though this should fail.

**Comment by swails** [comment]
> If there is no cpptraj binary though this should fail.

It doesn't :).  It runs through every test, tries to run, complains that there's no binary, and does no comparisons.  At the end, the summarizer finds that none of the 0 tests failed and merrily reports a successful build.  This is the end of that build:

```
make[1]: [Makefile:344: test.gromacs] Error 1 (ignored)
Error: cpptraj binary '../../bin/cpptraj' not found.
make[1]: [Makefile:345: test.gromacs] Error 1 (ignored)
===================== TEST SUMMARY ======================
No Test Results files (./*/Test_Results.dat) found.
=========================================================
make[1]: Leaving directory '/var/lib/jenkins/home/workspace/cpptraj/COMPILER_FLAGS/-openmp/test'
Finished: SUCCESS
```

The end of the current build is this:

```
===================== TEST SUMMARY ======================
  544 out of 545 comparisons OK (0 failed, 1 warnings).
  121 out of 121 tests completed with no issues.
=========================================================
make[1]: Leaving directory '/var/lib/jenkins/home/workspace/cpptraj/COMPILER_FLAGS/-openmp/test'
Finished: SUCCESS
```

So we're good to go, but I'll open an issue that a build in which every test errors before running a single comparison does not register as a failed build.

**Comment by drroe** [comment]
Good deal - thanks Jason!

**Pull request merged**
