### PR TITLE
Improve portability of the curvefit test

### PR DESCRIPTION
**Pull request by drroe**
The multi-exponential curve fit with a penalty function tends to not be very stable since the ordering of the exponential functions doesn't really matter. This PR changes the test slightly to just check the resulting curves, and check the specific parameters for the simpler multi-exponential fit instead. Also gives the multi-exponential + penalty test a better starting guess for some parameters to improve the stability. Hopefully this will go a ways towards improving test behavior with certain compilers.

### CODE REVIEW

**Comment by hainm** [comment]
"ERROR: Amber-MD GitHub » Test pytraj with cpptraj build `#55` completed with status FAILURE (propagate: false to ignore)"

@swails @drroe where can I see the failures?

**Comment by swails** [comment]
> @swails @drroe where can I see the failures?

On Jenkins.  It invokes the pytraj job, which is here: https://jenkins.jasonswails.com/job/amber-github/job/pytraj/

You can see the failed build.

**Comment by hainm** [comment]
Thanks. The failure is due to missing py.test. I will take a look.

**Comment by swails** [comment]
Then you'll need to update [this Dockerfile](https://github.com/Amber-MD/cpptraj/blob/master/devtools/ci/jenkins/Dockerfile.libcpptraj) to include it.

It uses a conda base image, so you should just be able to do a `conda install pytest` or `pip install pytest` or something inside the Dockerfile.

**Comment by hainm** [comment]
@swails  I think `pytest` should be added to the Jenkinfile you added in pytraj, right? 
https://github.com/Amber-MD/pytraj/blob/master/Jenkinsfile
(Update the `pip-requirements.txt`)

**Comment by swails** [comment]
> @swails I think `pytest` should be added to the Jenkinfile you added in pytraj, right?

That's the recipe that gets executed by cpptraj in order to test that pytraj works.  Please change it to whatever you think is appropriate.

**Comment by hainm** [comment]
thanks @swails. What should I do if I want to trigger the build again (I've updated pytraj repo)? Make a dummy PR to `cpptraj` repo? :D

**Comment by hainm** [comment]
run jenkins

**Comment by hainm** [comment]
The above magic words trigger the whole process (build/test cpptraj) in this PR again. Testing pytraj needs to wait that done.

**Comment by swails** [comment]
```
Collecting pytest==5.2.0 (from -r pip-requirements.txt (line 7))
  Could not find a version that satisfies the requirement pytest==5.2.0 (from -r pip-requirements.txt (line 7)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0, 2.9.1, 2.9.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 3.9.1, 3.9.2, 3.9.3, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5)
```

**Comment by hainm** [comment]
Thanks. I've just seen that too and I've updated pytraj. 
(Don't know why pytest 5.2.0 is not available. It's here: https://pypi.org/project/pytest/)

**Comment by hainm** [comment]
uhm, for unknown reason(s), pytraj tests stuck at the `pmap` testing:

Screen Shot 2019-10-02 at 11 26 53 PM

The test use 2 and 3 cores: https://github.com/Amber-MD/pytraj/blob/07296dfdb663a8bfdb45b8be6808636dd0d09517/tests/test_parallel_pmap/test_pmap.py#L174

**Comment by drroe** [comment]
@swails getting a `no cuda-capable device is detected` for the CUDA jenkins build.

**Comment by drroe** [comment]
Holy moly - PGI tests passed: https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fcpptraj/detail/cpptraj/121/pipeline/13

I hoped/expected to fix the cluster and curve fit tets, but not sure why the GIST tests for PGI are working now since I didn't make any fixes to them or the underlying code. Wonder if that's going to be a heisenbug...

**Comment by hainm** [comment]
May be pytraj’s parallel tests hang because they are running in docker env?

**Comment by swails** [comment]
> @swails getting a `no cuda-capable device is detected` for the CUDA jenkins build.

My Ubuntu node updated its kernel, which broke my NVIDIA driver. Reinstalling the driver and rebooting now.

**Comment by swails** [comment]
> May be pytraj’s parallel tests hang because they are running in docker env?

That explanation doesn't make sense.  It's only one parallel test.  You can pull the docker image yourself and try to run the tests in it to see if you can reproduce the hang.

**Comment by hainm** [comment]
> That explanation doesn't make sense. It's only one parallel test. You can pull the docker image yourself and try to run the tests in it to see if you can reproduce the hang.

I will try this tonight.

**Comment by drroe** [comment]
Heisenbug!

https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fcpptraj/detail/cpptraj/122/pipeline/13

@swails you have multiple runners right? Maybe it's related to which machine this actually runs on? I note that the PGI build on `batwoman` (https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/121/consoleFull) passes, while the PGI build on `Jenkins` (https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/122/consoleFull) does not. I think you use the `label` in the Jenkinsfile to determine runners for the CUDA build - could we do something similar for PGI?

**Comment by hainm** [comment]
Per pytraj: Updated pytraj's Jenkinsfile to exclude the parallel testing
```
 sh "cd tests && pytest -vs --ignore=test_parallel_pmap"
```

**Comment by drroe** [comment]
PGI failure again on `Jenkins`: https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/123/consoleFull

Everything else looks good though!

**Comment by hainm** [comment]
And pytraj’s partially full tests are run too.

I realize that python2 (jenkins uses py2)has some hanging issues with multiprocessing (used in pytraj).

**Comment by swails** [comment]
> @swails you have multiple runners right? Maybe it's related to which machine this actually runs on? I note that the PGI build on `batwoman` (https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/121/consoleFull) passes, while the PGI build on `Jenkins` (https://jenkins.jasonswails.com/job/amber-github/job/cpptraj/122/consoleFull) does not. I think you use the `label` in the Jenkinsfile to determine runners for the CUDA build - could we do something similar for PGI?

[We already do that for PGI](https://github.com/Amber-MD/cpptraj/blob/master/Jenkinsfile#L61).

Both master
image

and Batwoman
image

(and casegroup, but that machine is so slow due to the filesystem that it only connects when all other executors have been busy for over a minute with another job trying to get on)

have the `pgi` label.  You can adjust the label expression I linked above to force it onto one of the nodes.  To force it on Batwoman, change the label to:

```groovy
label 'pgi && Batwoman' // could just be 'Batwoman' since it's only one node
```

To force it onto the Jenkins master:

```groovy
label 'pgi && master' // could just be master since it's only one node
```

**Comment by drroe** [comment]
Thanks @swails. I'll add that today.

Any idea what might be different about `Jenkins` that causes the PGI tests to fail there? I can't seem to reproduce it anywhere else.

**Comment by swails** [comment]
Batwoman is a Xeon based workstation. Main Jenkins machine is a AMD processor. And Intel rules the world.

**Comment by drroe** [comment]
> Batwoman is a Xeon based workstation. Main Jenkins machine is a AMD processor. And Intel rules the world.

I see - we have some AMD boxes coming in next week so I'll be able to test then. Thanks for the info!

**Pull request merged**
