### PR TITLE
Fix assignment of "original" residue numbering during 'combinecrd'

### PR DESCRIPTION
**Pull request by drroe**
The "original" residue number should start from 1 to be consistent with how cpptraj assigns "original" residue numbers when none are present (i.e. when assigning from topology residue index).

### CODE REVIEW

**Comment by drroe** [comment]
@hainm can you take a look at the pytraj failure? Seems like it might be related to recent changes. https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fpytraj/detail/pytraj/188/pipeline

**Comment by hainm** [comment]
Ah yes, I decided to drop python 2 but jenkins is still using it.

Hai

**Comment by drroe** [comment]
I see. @swails how hard will that be to change? I looked at the JenkinsFile but didn't see an obvious way to change that. I guess it needs to be done in the docker image?

**Comment by swails** [comment]
It’s really easy. The dockerfile in this repo needs to be updated to use miniconda3 instead of miniconda. 

https://github.com/Amber-MD/cpptraj/blob/master/devtools/ci/jenkins/Dockerfile.libcpptraj#L1

**Comment by drroe** [comment]
@swails I'm seeing the following message at the end of the first shell script phase:
```
[2020-05-27T15:09:26.013Z] Cannot contact Batwoman: java.lang.InterruptedException
```
The build seems to be continuing though. Is this something to be concerned about?

https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fcpptraj/detail/PR-817/2/pipeline/191#step-208-log-1037

**Comment by hainm** [comment]
pytraj hangs again and I can reproduce it with the libcpptraj image. I am investigating now. For now, please run pytraj tests locally. :D 

This test seems causing the hang `test_createcrd.py::TestCreateCRD::test_autoimage_rms_strip`

uhm, travis test is ok: https://travis-ci.org/github/Amber-MD/pytraj/builds/691760477

**Comment by drroe** [comment]
```
========================== 412 passed, 40 skipped, 36 warnings in 28.58s ===========================
```
Tested with python 3.8.3 (anaconda 3). Going to merge.

**Comment by drroe** [comment]
@hainm Let me know if you want the warnings from pytraj tests.

**Comment by hainm** [comment]
> Let me know if you want the warnings from pytraj tests

please.

**Pull request merged**
