### PR TITLE
Make sure pytraj is tested with Python 3

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
@hainm  -- this is what happens in this PR: https://jenkins.jasonswails.com/job/amber-github/job/pytraj/121/

pytraj doesn't even build...

**Comment by hainm** [comment]
@swails It hangs due to failure to build numpy wheel. `pytraj` requires a specific numpy version (`v1.13.3`) for testing but it seems `numpy` binary wheel is not available in Jenkins platform (it's fine on travis). That is why `numpy` was built from source code. Weird. 

Screen Shot 2020-01-10 at 10 36 07 PM

**Comment by hainm** [comment]
I've remove version numpy to make sure pip picks up the latest version. Hopefully it's ok.

**Comment by drroe** [comment]
@swails does #818 make this obsolete?

**Pull request closed without merging**
