### PR TITLE
Merge in cmake-buildscripts v1.1

### PR DESCRIPTION
**Pull request by multiplemonomials**
I've been doing some reworking on the CMake build system, and the upshot is now that you can build _all_ configurations (MPI, OpenMP, CUDA, etc.) at the same time.  I also greatly improved how the packaging works; you can now separate things out into different packages by parallelization type.  Could you merge this so that I can get my changes merged to amber master?  Thanks.

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Hmmm looks like someone needs to agree to the xcode license on Jenkins:
```

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.

```

**Comment by drroe** [comment]
@multiplemonomials Something is odd about this PR - many files seem needlessly changed. For example, `devtools/Template.sh` is removed, `src/Analysis_State.h` and `src/CIFfile.h` have forward class declarations again, support for reading CHARMM output files is gone, etc. It's like this was based off of an old commit that is purposefully missing some updates but not others. Can you please make sure your changes are only affecting the files you intend?

**Comment by hainm** [comment]
@multiplemonomials 

```
git fetch origin
git checkout -b your_feature origin/master # where origin point to this repo, not your
# do some work, commit, add
git push your_remote_repo your_feature
# make a PR
```

PS: 
```
git remote add your_remote_repo https://github.com/multiplemonomials/cpptraj
```

**Comment by swails** [comment]
I'd vote for closing this or and trying again. i don't trust the history given that I don't understand how this PR reverts so many changes but still claims to be up to date with the master branch.

**Comment by drroe** [comment]
> I'd vote for closing this or and trying again.

This seems like the safest option. @multiplemonomials any objections?

**Comment by multiplemonomials** [comment]
Hmmm I guess so.  Not exactly sure what's happening here either.

**Pull request closed without merging**
