### PR TITLE
Fix 'temperature' action for removed global degrees of freedom

### PR DESCRIPTION
**Pull request by drroe**
Adds the `remove` keyword so that temperature calculation can account for removed translational and/or rotational degrees of freedom (e.g. an implicit solvent trajectory with CoM motion removed). Also adds an `update` keyword so the in-frame temperature can be updated (similar to the `time` action). Adds a test, updates docs.

Also adds a small section in the developers guide about what to do when modifying Topology/CoordinateInfo in Action::Setup().

### CODE REVIEW

**Comment by drroe** [comment]
Pytraj build on Jenkins is taking a while today...

**Comment by hainm** [comment]
omg, more than 5 hours. Not sure what happened.

**Comment by drroe** [comment]
Ok....I'm considering just merging this, but I'd like to know what happened with pytraj on Jenkins. @swails any insights?

**Comment by swails** [comment]
Looks like it just hung on casegroup...

**Pull request merged**
