### PR TITLE
Load a specific Amber so tests don't point to my test environment that

### PR DESCRIPTION
**Pull request by swails**
changes all the time.

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

I think the reason it didn't post the build results (which passed) is because I had reduced `AmberJenkins`'s role to Member in Amber-MD, whereas it needs to be an Owner :(

**Comment by swails** [comment]
there it goes.  @drroe -- can you merge this one before you open another PR?  This will reduce the likelihood of a false positive due to me playing with my local Amber build repo

**Comment by drroe** [comment]
Sorry for the delay, been traveling. Merging now.

**Pull request merged**
