### PR TITLE
Remove all references to '/dev/*' in test framework.

### PR DESCRIPTION
**Pull request by drroe**
Related to #750 and some of the changes in #747. File redirection in scripts should now be properly handled everywhere.

### CODE REVIEW

**Comment by drroe** [comment]
I don't get PGI compilers. Last Jenkins run (91) passed, now this one (92) fails. It's very arbitrary and I'm really inclined to just ignore it.

**Comment by swails** [comment]
If we're going to ignore the PGI fileaures (which I totally support), then we should remove that stage from the Jenkinsfile.

Keep in mind that Jenkins *also* is responsible for detecting pytraj breaks, but it only does that if all of the individual stages succeed.  So each time PGI fails and we ignore it, pytraj build/tests never get run with the proposed changes.

**Comment by drroe** [comment]
> If we're going to ignore the PGI fileaures (which I totally support), then we should remove that stage from the Jenkinsfile.

Long term I agree. I'd like to keep it for now to see if the failures really are random. If over the next few PR I get sometimes passing, sometimes failing I'll consider it too much of a pain to debug and disable it. However, if it's failing consistently I'd like to address that.

**Comment by swails** [comment]
Well at least we shouldn't block the pytraj tests from proceeding if the PGI builds fail.

**Comment by sbrozell** [comment]
Keep me,  @sbrozell , in the loop.
For context see
https://gitlab.ambermd.org/amber/amber/merge_requests/319

**Comment by sbrozell** [comment]
@drroe please include me in your repo; not sure what i need to do ... thanks

**Comment by hainm** [comment]
@sbrozell you can click "Watch" in the top page.https://help.github.com/en/articles/watching-and-unwatching-repositories

**Pull request merged**
