### PR TITLE
Improve configure, more PGI fixes.

### PR DESCRIPTION
**Pull request by drroe**
The following should hopefully address issues in #684.
- Implement convention in `minimage` that the first atom reported is always the one with the lowest index.
- Add the `-Mnoflushz` flag for PGI compiles to bring behavior more in line to GNU/Intel (fixes the binary comparison in the CCP4 test).

Also:
- Fixes configure so that FFTW header from MKL is correctly found (#682).
- Move SpaceGroup.cpp to front of compile; since it takes so long compiling it first saves some time during parallel makes.
- Fix the manual text for `help`.

### CODE REVIEW

**Comment by drroe** [comment]
Travis builds are failing because pysander appears broken.
```
$ curl -OL https://anaconda.org/AmberMD/pysander/16.0/download/linux-64/pysander-16.0-py27_1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   409    0   409    0     0   4351      0 --:--:-- --:--:-- --:--:--  4351
100 23838    0 23838    0     0   125k      0 --:--:-- --:--:-- --:--:--     0
$ file pysander-16.0-py27_1.tar.bz2 
pysander-16.0-py27_1.tar.bz2: HTML document, ASCII text, with very long lines
```
@hainm @swails any idea what's going on here?

**Comment by drroe** [comment]
OK, If I'm reading this right, pysander is no longer on anaconda under AmberMD: https://anaconda.org/AmberMD/repo

The only result when searching for `pysander` is under Hai's account (https://anaconda.org/hainm/pysander) but it hasn't been updated in about 3 years.

**Comment by hainm** [comment]
Uhm, @dacase or @swails: did you remove it since i did not.

**Comment by swails** [comment]
I already fixed this in my pull request. 

Merge my PR with this one and it’ll all just work.

**Comment by swails** [comment]
#684 fixed Travis (per my comment there).

**Pull request merged**
