### PR TITLE
add suppressoutput for clustering to avoid verbose in pytraj

### PR DESCRIPTION
**Pull request by hainm**
related to https://github.com/Amber-MD/cpptraj/issues/62

### CODE REVIEW

**Comment by hainm** [comment]
@drroe any suggestion about keyword? I am use 'suppressoutput' for input.

**Comment by swails** [comment]
What about `quiet`?

**Comment by hainm** [comment]
> What about quiet?

this PR only turns off a part of STDOUT about cluster info. I think `quiet` suggests there is not STDOUT at all. 

- full STDOUT from cpptraj

```bash
    CLUSTER: Using coords dataset DEFAULT_NAME, clustering using RMSD (mask [*]) best-fit
	K-MEANS: Looking for 10 clusters.
		Randomly pick points for modification.
		Seed for random number generator: 1
	Cluster to cluster distance will be based on cluster centroids.
	Starting clustering.
	Mask [*] corresponds to 5293 atoms.
	Calculating pair-wise distances.
	Estimated pair-wise matrix memory usage: > 0.244 kB
	Pair-wise matrix set up, 10 frames
67% Complete.
	Memory used by pair-wise matrix and other cluster data: 0.412 kB
	Round 0:  0% 11% 22% 33% 44% 56% 67% 78% 89% 100% Complete.
	K-means round 0: No change. Skipping the rest of the iterations.
#Clustering: 10 clusters 10 frames
#Cluster 0 has average-distance-to-centroid 0.000000
#Cluster 1 has average-distance-to-centroid 0.000000
#Cluster 2 has average-distance-to-centroid 0.000000
#Cluster 3 has average-distance-to-centroid 0.000001
#Cluster 4 has average-distance-to-centroid 0.000001
#Cluster 5 has average-distance-to-centroid 0.000001
#Cluster 6 has average-distance-to-centroid 0.000000
#Cluster 7 has average-distance-to-centroid 0.000001
#Cluster 8 has average-distance-to-centroid 0.000001
#Cluster 9 has average-distance-to-centroid 0.000000
#DBI: 0.000000
Warning: Each frame is in a separate cluster. Not calculating pseudo-F.
#Algorithm: Kmeans nclusters 10 maxit 100
#Representative frames: 1 10 5 7 8 6 3 4 2 9
	Cluster timing data:
TIME:	  Cluster Init. : 0.0000 s (0.00%)
TIME:	  Pairwise Calc.: 0.0033 s (8.07%)
TIME:	  Clustering    : 0.0138 s (34.27%)
TIME:	  Cluster Post. : 0.0232 s (57.64%)
TIME:	Total: 0.0403 s
```

- If specify `suppressoutput` (or alternative keyword): No cluster info (average-distance-to-centroid)

```bash
    CLUSTER: Using coords dataset DEFAULT_NAME, clustering using RMSD (mask [*]) best-fit
	K-MEANS: Looking for 10 clusters.
		Randomly pick points for modification.
		Seed for random number generator: 1
	Cluster to cluster distance will be based on cluster centroids.
	Starting clustering.
	Mask [*] corresponds to 5293 atoms.
	Calculating pair-wise distances.
	Estimated pair-wise matrix memory usage: > 0.244 kB
	Pair-wise matrix set up, 10 frames
44% Complete.
	Memory used by pair-wise matrix and other cluster data: 0.412 kB
	Round 0:  0% 11% 22% 33% 44% 56% 67% 78% 89% 100% Complete.
	K-means round 0: No change. Skipping the rest of the iterations.
	Cluster timing data:
TIME:	  Cluster Init. : 0.0000 s (0.01%)
TIME:	  Pairwise Calc.: 0.0033 s (16.73%)
TIME:	  Clustering    : 0.0140 s (70.78%)
TIME:	  Cluster Post. : 0.0025 s (12.45%)
TIME:	Total: 0.0198 s
Out[35]: array([0, 8, 6, 7, 2, 5, 3, 4, 9, 1], dtype=int32)
```

And this is pytraj's wishlist by adding this PR
```python
In [37]: pt.cluster.kmeans(traj, options='suppressoutput')
Out[37]: array([0, 8, 6, 7, 2, 5, 3, 4, 9, 1], dtype=int32)
```

**Note**: User still see cpptraj's STDOUT if `pytraj._verbose(True)`
cpptraj has different mechanism for verbose :))

**Comment by swails** [comment]
> I think quiet suggests there is not STDOUT at all.

So does `suppressoutput` to me

**Comment by hainm** [comment]
> So does suppressoutput to me

Yes, you're right. Just wondering if we just add a tag in cpptraj input for pytraj (hide from user).

Probably we just use 'quiet' (I always favor short word) and do not document this keyword (for pytraj only).

**Comment by swails** [comment]
> Probably we just use 'quiet' (I always favor short word) and do not document this keyword (for pytraj only).

+1 for this.  Maybe earmark this keyword for other actions where you want something similar.

Maybe Dan has advice/preferences on how to generally accomplish this task.

**Comment by drroe** [comment]
> Probably we just use 'quiet' (I always favor short word) and do not document this keyword (for pytraj only).

From my brief glance at the code I gather that what this does specifically is prevent cpptraj from writing to the `info` file. So what about `noinfo`, and making the variable `supressInfo_`? Also, I'm OK with making it a hidden option since it's really only relevant for pytraj. Also, I'm wondering if there should be some sort of warning if `info` and `noinfo` are specified together - could this ever conceivably happen with pytraj?

Also, this code:
```C++
if (analyzeArgs.hasKey("suppressoutput"))
  suppressOutput_ = true;
else
  suppressOutput_ = false;
```
Can be written more concisely as:
```C++
suppressOutput_ = analyzeArgs.hasKey("suppressoutput");
```

**Comment by hainm** [comment]
> From my brief glance at the code I gather that what this does specifically is prevent cpptraj from writing to the info file. So what about noinfo, and making the variable supressInfo_?

updated

> Also, I'm OK with making it a hidden option since it's really only relevant for pytraj.

removed info from Help

> Also, I'm wondering if there should be some sort of warning if info and noinfo are specified together - could this ever conceivably happen with pytraj?

I have tendency to turn off all cpptraj's STDOUT and the verbose is only for debugging. pytraj starts from fresh so there is no problem with backward compat like cpptraj. (Ideally pytraj should be consistent with cpptraj).

PS: if user wants to completely use `cpptraj` style inside pytraj, he/she can always use `CpptrajState`

**Comment by drroe** [comment]
Seems good. Thanks.

**Pull request merged**
