### PR TITLE
Fix test differences with PGI compilers

### PR DESCRIPTION
**Pull request by drroe**
This MR at long last should address #841. It includes some small fixes and reworks some tests so that the code will return nearly identical results to GNU/Intel compilers.

- The best-representative code in clustering was reworked so that 1 and 2 member clusters are handled in a more consistent manner.
- The symmetric RMSD clustering test uses a more realistic trajectory. The artificial trajectory had too many identical frames, and the zeros in the pairwise matrix could lead to unpredictable behavior.
- In curve fitting, one loop in the Householder transformations was forced to de-optimize, which seems to bring the PGI results more in line with GNU/Intel.
- Tolerances were relaxed slightly for the `evalplateau` test.
- In the GIST test, a vector sign check was made more numerically stable by comparing to `Constants::SMALL` instead of zero.

### CODE REVIEW

**Comment by drroe** [comment]
@swails from Jenkins:
```
All nodes of label ‘linux’ are offline
```
Will they be back up soon?

**Comment by drroe** [comment]
Jenkins is back! Yay!

**Comment by drroe** [comment]
PGI build passed!

**Comment by swails** [comment]
The Jenkins nodes actually shut down and reboot (via wake on lan) as they are needed.

Doing that I was able to cut the power usage from 20-25 kWH per week to ~5 kWH per week. 

It's actually a pretty nifty bit of code if I do say so myself, as was the setup to actually monitor the usage. 

But what that means is that it may take about 2-3 minutes after a job is submitted before an agent comes online to execute it.

**Comment by swails** [comment]
@drroe do you want me to make pgi failures fatal again now that they should be passing?

**Comment by drroe** [comment]
> The Jenkins nodes actually shut down and reboot (via wake on lan) as they are needed.

That is awesome!

> do you want me to make pgi failures fatal again now that they should be passing?

The lazy person in me wants to say no, but since I have access to the compilers now and can test them more regularly I guess PGI errors should be fatal. I just wish I had a sense of whether they're still worth actively supporting or not. I haven't used them in a production capacity since I was at the University of Utah (so < 2016).

**Comment by swails** [comment]
The most compelling argument to me is that using multiple compilers increases the likelihood of finding subtle bugs.  Obviously this argument falls apart when most of what you uncover are compiler bugs.

My take here is that the core issues were as much problematic tests (susceptible to numerical instability) as flaky compilers.  If the net result of fixing PGI compatibility was the introduction of more realistic test cases with more robust and well-defined behavior, then I'd argue that's a good thing.  De-optimizing a loop to work around a compiler bug is a bad thing.  If the latter is minor, then I think gating on PGI passing is good, but I defer to you.

**Pull request merged**
