### PR TITLE
Add LGTM badge.

### PR DESCRIPTION
**Pull request by drroe**
This will also serve to test the LGTM automated code review integration.

### CODE REVIEW

**Comment by drroe** [comment]
1 of the 3 Appveyor tests is hanging again. Going to merge.

**Comment by hainm** [comment]
> 1 of the 3 Appveyor tests is hanging again.

Just FYI:"Microsoft will be shipping a Linux kernel with Windows"
https://devblogs.microsoft.com/commandline/announcing-wsl-2/

cc @dacase @swails :D

**Comment by swails** [comment]
> Just FYI:"Microsoft will be shipping a Linux kernel with Windows"
> https://devblogs.microsoft.com/commandline/announcing-wsl-2/

I've used WSL-1 a decent amount (many people at Lutron have used it much more).  It's great for many things, and I like that MS is doubling down on this effort.  However, it's irrelevant here.  It's a Linux Kernel running in a virtualized environment alongside Windows.  Not much is changing, except the VM it runs in is becoming slimmer and the filesystem interface is being made not-the-worst.

But you can't run Linux binaries from Windows system calls (cmd or powershell) or from a Windows program system call.  You also can't run Windows programs from the bash shell (*unlike* msys or cygwin, where you basically get full compatibility).  I've also had worse than bad luck getting any GUI programs to work, and I don't know how the WSL works with resources it needs to share with Windows (for instance, nginx or apache vs. IIS).

If you're going to publicly support Windows computers through WSL, what you are saying is "we do not support Windows, but you can run it on a Windows PC through the Linux compatibility layer".  You can't use Windows-conda to install and run linux extensions like pysander -- libsander will _still_ need to build native on Windows outside of WSL.  And if Phenix is primarily a Windows tool, WSL won't help integrating with them at all.

**Comment by swails** [comment]
> This will also serve to test the LGTM automated code review integration.

A+ for both C++ _and_ JavaScript!  You should check for Rust and Scala too and rack up the A+s :smiley:

**Comment by drroe** [comment]
> A+ for both C++ and JavaScript! You should check for Rust and Scala too and rack up the A+s 😃
Ha! The JavaScript thing confused me. I think it’s somehow triggered by the lgtm.yml file itself.

**Comment by swails** [comment]
Do you have a .js or a .ts file anywhere?

**Comment by drroe** [comment]
> Do you have a .js or a .ts file anywhere?

Nope, but on the LGTM overview, if I filter by language: javascript the only commit that shows lines added is 'Add lgtm YML file'. It's strange. The only thing I can think of is maybe it scans the lgtm YML file to make sure you don't break that file, but for some reason it's classified as javascript. I'd mind more if it wasn't an A+ :smile:

**Pull request merged**
