### PR TITLE
Make an option to use LIE without PBC. 

### PR DESCRIPTION
**Pull request by swails**
It was easy enough to do it.

### CODE REVIEW

**Comment by drroe** [comment]
Nice, thanks @swails for doing this. Sorry for the delay in getting to this - working from home + toddler makes for very busy days (I'm sure you can relate!). 
Could you bump the revision number in `Version.h`? Then all will be GtG!

**Comment by drroe** [comment]
Oh wait...maybe I can do it by pushing to this branch...

**Comment by swails** [comment]
I'm trying to renew my Intel compiler non-commercial license.  They only last 1 year and they're getting increasingly strict and slow about approving open source (free) licenses.

I'm about to give up and just drop the Intel stage altogether.

**Comment by swails** [comment]
FYI, my intel licenses have been renewed.  The Intel stages should start building correctly again.

**Pull request merged**
