### PR TITLE
WIP - Playing with conda env for now (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by hainm** [comment]
um, there are two conda programs now. 

```
Run # $CONDA is an environment variable pointing to the root of the miniconda directory
  # $CONDA is an environment variable pointing to the root of the miniconda directory
  echo $CONDA/bin >> $GITHUB_PATH
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
```

```
Run which conda
/usr/share/miniconda/bin/conda
```

**Comment by drroe** [comment]
Well $CONDA/bin/conda appears to be the one segfaulting:
https://github.com/Amber-MD/cpptraj/actions/runs/8177232131/job/22358432147?pr=1068

Do you think I should try the /usr/share/miniconda one? Or something else?
I'm really in the weeds here.

**Comment by hainm** [comment]
Yeah we should use the same version to run.

**Comment by drroe** [comment]
So actually that is the one that fails:

$ /usr/share/miniconda/bin/conda env update --file
devtools/ci/environment.yml --name base

See https://github.com/Amber-MD/cpptraj/actions/runs/8177232131/job/22358432147?pr=1068

Is there somewhere else I should be looking?

**Comment by hainm** [comment]
> Is there somewhere else I should be looking?

I will do this. cheers.

**Comment by hainm** [comment]
> > Is there somewhere else I should be looking?
> 
> I will do this. cheers.

@drroe green now. Please include the change in this PR to yours. cheers.

**Comment by drroe** [comment]
Thanks Hai, you're awesome!

**Comment by hainm** [comment]
Yay, i was just trying to soothe your Python pain. 😂

**Pull request closed without merging**
