### PR TITLE
Adding in support for Amber netcdf trajectories with forces

### PR DESCRIPTION
**Pull request by ctlee**
Very minor addition to support the reading and writing of Netcdf trajectories with forces. The modifications pass the included unit tests. Here is an output of Summary.sh:

bash-4.2$ ./Summary.sh 
-rwxr-xr-x 1 clee mccammon 4311732 Oct 28 16:39 /net/home/clee/.local/cpptraj/bin/cpptraj
**************************************************************
TEST: /net/home/clee/.local/cpptraj/test
===================== TEST SUMMARY ======================
  241 out of 241 comparisons OK (0 failed).
  62 out of 62 tests completed with no issues.
ls: cannot access */Test_Error.dat: No such file or directory
=========================================================

### CODE REVIEW

**Comment by hainm** [comment]
@ctlee why do you close this PR? don't want to add this anymore?

**Comment by ctlee** [comment]
Failed a visual inspection. Should be pretty trivial to fix, will resubmit
it hopefully tomorrow, when working!

On Wednesday, October 28, 2015, Hai Nguyen <notifications@github.com> wrote:

> @ctlee <https://github.com/ctlee> why do you close this PR? don't want to
> add this anymore?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/pull/143#issuecomment-152040413>.
>


-- 
_
Christopher T. Lee M.Sc
Ph.D. Student - Amaro & McCammon Group
Department of Chemistry & Biochemistry
University of California, San Diego

Phone: +1 (858) 534-0956
ctlee@ucsd.edu

**Comment by hainm** [comment]
yeah I see. In the future, you just leave the PR open and keep pushing new commits when you have time.

**Comment by ctlee** [comment]
Ah ok got it!

**Comment by drroe** [comment]
Also, when finished could you add a small test case for this if possible?

**Pull request closed without merging**
