### PR TITLE
Trap program errors and missing binary errors during testing

### PR DESCRIPTION
**Pull request by drroe**
Addresses #453

### CODE REVIEW

**Comment by swails** [comment]
Jenkins failure looks real here.  It's only in the MPI build

**Comment by swails** [comment]
Here are the 3 errors:

```
TEST: /var/lib/jenkins/home/workspace/cpptraj/COMPILER_FLAGS/-mpi/test/Test_GromacsXtc

  CPPTRAJ: XTC read test
Error: NetCDF single trajectory output in parallel requires Pnetcdf.
Error: Could not set up parallel trajout.
Error: Problem with set up or format may be unsupported in parallel.
Error: Setting up output trajectory 'cpptraj.nc' in parallel.
Error: Error(s) occurred during execution.
Error: cpptraj exited with status 1
```

```
TEST: /var/lib/jenkins/home/workspace/cpptraj/COMPILER_FLAGS/-mpi/test/Test_KDE

  CPPTRAJ: KDE test.

  CPPTRAJ: KDE with Kullback-Leibler divergence test.
Error: cpptraj exited with status 1
All 3 comparisons passed.
```

The last error is also a Pnetcdf issue.  Should I just install pnetcdf on that machine?

**Comment by drroe** [comment]
> The last error is also a Pnetcdf issue. Should I just install pnetcdf on that machine?

Yes, but I need to make it so that those tests won't run if pnetcdf not compiled. Thanks for the report!

**Comment by drroe** [comment]
@swails Can you post more details about the Test_KDE error? I can't reproduce it and the test shouldn't depend on parallel netcdf anyway.

**Comment by drroe** [comment]
OK, I've been able to reproduce the error. Working on it now.

**Comment by drroe** [comment]
Turned out to be a legit bug. All should be well now. Fingers crossed...

**Comment by swails** [comment]
Go CI!

**Comment by drroe** [comment]
@swails If you were serious about moving the Mac build to Jenkins I am all for it. These delays are a bummer...

**Comment by drroe** [comment]
Alternatively I can see if maybe they'll host a Mac buildbot at U. Utah or something

**Comment by swails** [comment]
[I configured my Mac Mini as a slave last night](http://www.jasonswails.com:8888/computer/Mac-Mini/), but that's the easy part.  What remains to be done is:

1. Add another configuration axis with the OS
2. Prune the axis combos I don't want to run
3. Modify the Jenkins script to run on Mac OS X and Linux (with Intel) based on the build environment
4. Get it to work

If you wanted to take a crack at it, your login creds to my Jenkins server should give you permission to do so.  Otherwise I should be able to make progress on it this weekend.

**Comment by drroe** [comment]
Ugh - the build timed out...restarting.

**Comment by drroe** [comment]
@swails If I get a chance tonight I may try.

**Comment by drroe** [comment]
Got there

**Pull request merged**
