### PR TITLE
Read ph remlog

### PR DESCRIPTION
**Pull request by drroe**
Addresses #26 and improves remlog analysis functionality in general. Can now read in pH REMD logs. Exchange acceptance calc has been improved (now handles lowest->highest exchange) and is broken down by dimension for MREMD. Round-trip calculation is also broken down by dimension for MREMD.

### CODE REVIEW

**Comment by swails** [comment]
Awesome -- can you merge this back to the Amber repo so @roitberg (or someone in his group) can try it out more easily?

**Comment by roitberg** [comment]
Hi
BTW: I have been superbusy with things, but afaik, it woks !

thanks Dan !


On 9/23/15 11:39 AM, Jason Swails wrote:
>
> Awesome -- can you merge this back to the Amber repo so @roitberg 
> <https://github.com/roitberg> (or someone in his group) can try it out 
> more easily?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Amber-MD/cpptraj/pull/80#issuecomment-142642384>.
>

-- 
Dr. Adrian E. Roitberg
Professor.
Department of Chemistry
University of Florida
roitberg@ufl.edu
352-392-6972

**Comment by drroe** [comment]
> Awesome -- can you merge this back to the Amber repo so @roitberg (or someone in his group) can try it out more easily?

@swails Sure, but as far as I know it has to be in that `master_with_cpptraj_on_github` branch right? We never figured out the history pollution stuff.

**Comment by swails** [comment]
> We never figured out the history pollution stuff.

Yea, from everything I can tell it's too late now.  Screw it, just merge it :).

**Comment by hainm** [comment]
> Screw it, just merge it 

:+1: :+1:

**Comment by drroe** [comment]
For now I've kept it on the master_with_cpptraj_on_github branch of the Amber GIT repo. If I (or someone else) ever feels comfortable it's easy enough to merge that into master at some point.

**Comment by swails** [comment]
I think we can just merge it.  The only way to avoid this history duplication is to go back and re-do the subtree split an entirely different way.  It's much too late for that.  There is no avoiding the merge (and the additional space has already been added to the repository in a different branch), so there's really nothing to be gained by keeping it separate anymore.

**Comment by hainm** [comment]
Agree

**Comment by drroe** [comment]
It is done.

**Comment by hainm** [comment]
oh, just remember that ``pytraj`` needs cpptraj, so if you did not merge, it (pytraj) is useless. :D

**Comment by hainm** [comment]
@drroe can you update the test (or send me via email) for remlog? I want to start working with this on pytraj. Need to see the syntax, real-world example, data ...

**Pull request merged**
