### PR TITLE
Check for skewed non-orthogonal box

### PR DESCRIPTION
**Pull request by drroe**
If box is too skewed to perform accurate imaging with current imaging routines, it is disabled.

@rmcgibbo If you get a chance would you mind checking this out? I tested on the system you originally provided and it seemed to work OK.

### CODE REVIEW

**Comment by drroe** [comment]
Should address #223

**Comment by swails** [comment]
I think better behavior is to keep the box on and just warn that computed distances *might* not be the absolute minimum.  The distances will be correct for any atom that lies within the radius of the largest sphere that can be circumscribed within the unit cell.  You could even compute what that distance would be and say something like "any distance below XYZ will be correct, other distances may not be the closest image because the unit cell is too skewed"

**Comment by drroe** [comment]
> I think better behavior is to keep the box on and just warn that computed distances might not be the absolute minimum. 

I could potentially get on board with that. My only hesitation is that when most Actions perform imaging, cpptraj is *supposed* to adhere to the minimum image convention. When the box is skewed like this there is no guarantee that it can do this, so even though you're returning a closer distance it's not always going to be the *minimum* distance, and so technically it's wrong. In other words I'm not sure that returning an arbitrarily closer distance is better than just saying "well I know I'm going to fail sometimes so I won't even try", which seems more honest.

Although truth be told this is such a corner case that my feeling is that it won't matter for 99.9% of users...

**Comment by drroe** [comment]
@swails OK I've come around to your way of thinking - give the user info and let them decide what to do. Otherwise the box info is always automatically removed which is bad.

**Pull request merged**
