### PR TITLE
Improve handling of atom names/type names/residue names under the hood

### PR DESCRIPTION
**Pull request by drroe**
The NameType class no longer formats names to be exactly 4 characters, left-aligned, filled with spaces if necessary; this was very Amber-centric and could result in name mismatches. Formatting is now handled by any output routines, as it should be. Care has been taken to preserve as much backwards compatibility in output (in terms of name formatting) as possible, but some differences are possible. In particular, no effort has been made to preserve compatibility with `comparetop` since I like the new format better and I don't think the command is heavily used (it's still listed as "experimental" anyway).

In addition, cpptraj **no longer replaces asterisks in atom/residue names with single quotes**. This was done originally to avoid issues with mask selection syntax (since `*` is a wildcard). However, for some time the mask parser has been fine with taking `\*` to mean "literal asterisk", so the code that swaps out asterisks for quotes is not only anachronistic, but it's a more or less silent change and I've always despised it. So now that's gone and I'm happier.

The code under the hood in Jcoupling has been improved; there may be performance benefits although I haven't tested. At any rate I like the code better now.

### CODE REVIEW

**Comment by swails** [comment]
pytraj broke:

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
pytraj/core/c_core.cpp: In function ‘PyObject* __pyx_pf_6pytraj_4core_6c_core_8NameType_18replace_asterisk(__pyx_obj_6pytraj_4core_6c_core_NameType*)’:
pytraj/core/c_core.cpp:7468:26: error: ‘class NameType’ has no member named ‘ReplaceAsterisk’
   __pyx_v_self->thisptr->ReplaceAsterisk();
                          ^~~~~~~~~~~~~~~
pytraj/core/c_core.cpp: At global scope:
pytraj/core/c_core.cpp:6779:18: warning: ‘PyObject* __pyx_pw_6pytraj_4core_6c_core_8NameType_7__str__(PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_pw_6pytraj_4core_6c_core_8NameType_7__str__(PyObject *__pyx_v_self) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: command 'gcc' failed with exit status 1
[Pipeline] }
```

That's why the Jenkins build failed.

**Comment by drroe** [comment]
Yeah, I'm working on a pytraj fix now...hope to have it done soon

**Comment by hainm** [comment]
> That's why the Jenkins build failed.

image

**Comment by hainm** [comment]
> pytraj/core/c_core.cpp:7468:26: error: ‘class NameType’ has no member named ‘ReplaceAsterisk’

I was so naive to expose lots of cpptraj's function. This class should be cleaned up in `pytraj` too.

**Comment by hainm** [comment]
@drroe Can you please submit a PR to remove those lines in pytraj? thanks
(can not work on this right now)

https://github.com/Amber-MD/pytraj/search?utf8=%E2%9C%93&q=ReplaceAsterisk&type=

**Comment by drroe** [comment]
I'm hoping https://github.com/Amber-MD/pytraj/pull/1496 will fix pytraj once this is merged.

**Comment by drroe** [comment]
run jenkins

**Comment by swails** [comment]
> run jenkins

I don't think that works from GitHub.  You need to retrigger it from Jenkins itself (I just did that, but your login can do it, too).

**Comment by drroe** [comment]
I think we just triggered builds at the same time ... oops

**Comment by drroe** [comment]
And I think I triggered the wrong thing - hopefully your trigger has more success.

**Pull request merged**
