### PR TITLE
molsurf/rmsf/dihedral chi/ARPACK

### PR DESCRIPTION
**Pull request by drroe**
This PR addresses several open issues:

#88 For the `dihedral` action `chi` is now an alias for `chin` to preserve backwards compatibility with ptraj.
#108 Users can now compile with `-noarpack` if desired; this will use the full eigenvector calculation under the hood but only save the specified number (which can get expensive for large numbers of eigenvectors).
#102 Added keyword `[radii {gb | parse | vdw}]` to `molsurf` action to enable different radii sets. Cleaned up `molsurf`.
#128 `rmsd` is now an alias for `atomicfluct`

### CODE REVIEW

**Comment by hainm** [comment]
> For the dihedral action chi is now an alias for chin to preserve backwards compatibility with ptraj.

I personally stiff don't like this. But ... it's for backward.

**Comment by hainm** [comment]
> rmsd is now an alias for atomicfluct

do you mean 'RMSF'?

**Comment by drroe** [comment]
> do you mean 'RMSF'?

Yes, rmsf

**Comment by swails** [comment]
> I personally still don't like this. But ... it's for backward.

What about doing wild-card recognition?  So `chi*` selects both `chin` and `chip`?

**Comment by hainm** [comment]
@swails  

> So chi* selects both chin and chip?

:+1:  :+1:

**Pull request merged**
