### PR TITLE
Fix for pytraj

### PR DESCRIPTION
**Pull request by drroe**
Make `PDBWRITEMODE` public again (done in #474) to fix pytraj build, and add a note so I don't forget.

### CODE REVIEW

**Comment by drroe** [comment]
This is frustrating - there's an SSL error with anaconda for pysander that is causing everything to fail.

**Comment by hainm** [comment]
that's why I told @dacase that we should host our own binary distribution in ambermd.org server. (@Dave: from our discussion with John Chodera). Anaconda is very popular now so people tends to use it alot.

**Comment by drroe** [comment]
Looks like switching to Trusty has fixed the issue, but for some reason the OpenMP build is just sitting in the queue.

**Comment by drroe** [comment]
At long last...

**Pull request merged**
